spring:
  application:
    name: login-auth-api
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:db_login
    initialization-mode: always
    driver-class-name: org.h2.Driver
    username: h2
    password: 123

api.security.token:
    secret: "my-secret-key"